package Configurações;



import Templates.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Utilizador
 */
public class Perfil_List extends javax.swing.JFrame {

    /**
     * Creates new form EquipmentList
     */
    public Perfil_List() {
        initComponents();
        PopulateTable();
        
    }
    public static String[] GetColumns(){
   String columns[] = {"Nome","Descricao"};
    return columns;
};

    
    
    public void PopulateTable() {
    try{
    int i=0;
    String Connection = "jdbc:derby://localhost:1527/ScoutsDB_DEV";
    Connection con=DriverManager.getConnection(Connection,"AdminA","123456");  
    Statement st = con.createStatement();
    String query_Select = "Select * from PERFIS";
    ResultSet rs = st.executeQuery(query_Select);
    ResultSetMetaData rsmd= rs.getMetaData();
    DefaultTableModel model = (DefaultTableModel) EquipmentTable.getModel();
    
    //Criação de colunas
     String[] columns = new String[3];
     
     columns[0] = rsmd.getColumnName(2);
     columns[1] = rsmd.getColumnName(3);
     columns[2] = "ID";
     
    model.setColumnIdentifiers(columns);
    
    //Criação das linhas
    while(rs.next()){
     String data[] = {rs.getString(2),rs.getString(3),rs.getString(1)};
     
    model.addRow(data);
    }
    st.close();
    con.close();
     
    }catch(Exception e){e.printStackTrace();};
           
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        EquipmentTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        EquipmentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        EquipmentTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EquipmentTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(EquipmentTable);
        EquipmentTable.getAccessibleContext().setAccessibleName("");

        jButton1.setText("Criar novo perfil");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EquipmentTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EquipmentTableMouseClicked
        // TODO add your handling code here:
        Perfil_DetailPage EDP;
        try {
        int column = 2;
        int row = EquipmentTable.getSelectedRow();
        String value =  EquipmentTable.getModel().getValueAt(row, column).toString();            
        EDP = new Perfil_DetailPage(Integer.parseInt(value));
        EDP.show();
        dispose();
        
          } catch (SQLException ex) {
            Logger.getLogger(Perfil_List.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_EquipmentTableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Perfil_InsertPage InsertPage = new Perfil_InsertPage();
        InsertPage.show();
        dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Perfil_List().setVisible(true);
            }
        
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable EquipmentTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
